### ISSUE TITLE
Redux ⚔️ Context for dapp

### ISSUE THREAD

**Issue by 0xNilesh** [ethereum-push-notification-service/push-dapp#647]
Need a discussion for deciding b/w context and redux for the whole dapp.

**Comment by mishramonalisha76** [comment]
According to my research redux seemed better for a bigger application like push'(especially because it will scale even more).
Redux is better for dynamic data which changes more frequently. Context is more for static data(theme, navigation data). chat has alot of data changing frequently. 
Some articles i went through [https://www.codehousegroup.com/insight-and-inspiration/tech-stream/using-redux-and-context-api](https://www.codehousegroup.com/insight-and-inspiration/tech-stream/using-redux-and-context-api)

**Comment by 0xNilesh** [comment]
![image](https://user-images.githubusercontent.com/54444545/207310147-e8d336ee-da07-47ad-a051-2561137a3ba1.png)
[Image from React Official Docs]

Acc to my knowledge/research, Context is suitable for static data that is less frequent.
![image](https://user-images.githubusercontent.com/54444545/207311001-c6723e7f-6076-4b60-a507-c5be78523c0a.png)
[Image from React Official Beta Docs]

It states, for complex state management, use Context + useReducer hook
And Afaik, Redux does the better version of this and doing Context + reducer is kinda re-inventing a weaker version of Redux.
I'd recommend using Redux, but definitely open for discussions around this.

Some research:
![image](https://user-images.githubusercontent.com/54444545/207312041-9e47130d-a6a7-445d-8155-5a32b6945175.png)
[Image from a article from Redux Maintainer, for full article - go to references in the comment]

References:
https://reactjs.org/docs/context.html
https://beta.reactjs.org/learn/passing-data-deeply-with-context#use-cases-for-context
https://blog.isquaredsoftware.com/2021/01/context-redux-differences/

**Comment by 0xNilesh** [comment]
Internal discussion conclusion: We'll proceed with Context
