### ISSUE TITLE
Verified by on Push dapp

### ISSUE THREAD

**Issue by richajoshi123** [ethereum-push-notification-service/push-dapp#685]
The dapp "verified by" field for channels points to Ethereum Push Notification Service. It should say "Push Protocol"

link: https://app.push.org/#/channels

Can this corrected?

**Comment by zaryab2000** [comment]
Yes, @richajoshi123 

This issue is already created and will be addressed with the launch of the **"The UpdateChannelMeta"** feature.

Basically, once we change the EPNS Channel's name on prod  to Push Protocol - all **Verified by** channel names will be automatically replaced with **Push Protocol**

Closing this issue since the original issue already exists here #386
